project:
  type: website

website:
  title: "Finjustering av språkmodell på Nav.no"
  description: "Introduksjon til finjustering av språkmodeller på data fra Nav.no"

  image: assets/cover.png
  image-alt: "Illustrasjon som uthever finjustering av en språkmodell"
  search: false
  repo-url: https://github.com/navikt/navno_finetune
  repo-actions: [source, issue]
  twitter-card: true
  open-graph: true

  navbar:
    logo: assets/nav_logo.png
    logo-alt: "Logo til NAV - Arbeids- og velferdsetaten"
    left:
      - text: "Veiledning"
        href: index.ipynb
      - text: "Oppsett av TPU"
        href: tpu.qmd
    right:
      - icon: slack
        href: https://nav-it.slack.com/archives/C04MRJ9SHM4
        aria-label: Slack kanal for kontakt
      - icon: people-fill
        href: https://teamkatalog.nav.no/team/415e12bc-61fb-4579-840a-c9307765f2fc
        aria-label: Ansvarlig team hos NAV

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    highlight-style: atom-one
execute:
  eval: false
